<?php

// $data = $_GET;
// if(!key_exists("enseigne",$data) || empty($data["enseigne"])) die("Error");

// $domaine = "net2all.online";
// $sousdomaine = "erp.net2all.online";

// $enseigne = str_replace(" ", "_",$data["enseigne"]);

// $enseignerr = str_replace(" ", "",$data["enseigne"]);


// //echo $domaine;


// $domainepath="/var/www/vhosts/net2all.online/erp.net2all.online";

// $api_url ="https://$sousdomaine/$enseigne/htdocs/api/";
// $magmaapikey="";


// $characters = 'a3HIuxyzAB2ST4K5vw6cQRUde7bfgMNGhijklmnYZoCDSpq89rstEFL3JOPVW01X';
// $charactersLength = strlen($characters);
// $uniqid = '';
// $length=32;
// for ($i = 0; $i < $length; $i++) { // $uniqid .=$characters[rand(0, $charactersLength - 1)]; // } // /* //
    $lengthkey=75; // for ($i=0; $i < $lengthkey; $i++) { // $magmaapikey .=$characters; // } // */ //
    $magmaapikey="a3HIuxyzAB2ST4K5vw6cQRUde" ; // $param=[ // "api_url"=>$api_url,
    // "magmaapikey"=>$magmaapikey ,
    // "ok" => "erp_$enseigne"
    // ];


    // $servername = "127.0.0.1" ;
    // $username = "erp".$enseignerr ;
    // $password = "S6p4s9J7G5o8W5W" ;
    // $dbname="erp_$enseigne" ;

    // $file="$domainepath/$enseigne/htdocs/conf/conf.php";
    // $enseignequery="mkdir " . $domainepath . "/" . $enseigne;
    // $querydeletefile="rm -f ".$file;
    // $fullpath=$domainepath."/".$enseigne;
    // $copyquery = "cp -r install_new/* ".$fullpath;

    // //echo $query;
    // exec($enseignequery);
    // exec($copyquery);
    // exec($querydeletefile);
    // //echo $copyquery;



    // $confdata = '?php
    // //
    // // File generated by Dolibarr installer 13.0.2 on 25 Juil. 2021
    // //
    // // Take a look at conf.php.example file for an example of conf.php file
    // // and explanations for all possibles parameters.
    // //
    // $dolibarr_main_url_root=\'https://'.$sousdomaine.'/'.$enseigne.'/htdocs\';
    // $dolibarr_main_document_root=\''.$fullpath.'/htdocs\';
    // $dolibarr_main_url_root_alt=\'/custom\';
    // $dolibarr_main_document_root_alt=\''.$fullpath.'/htdocs/custom\';
    // $dolibarr_main_data_root=\''.$fullpath.'/documents\';
    // $dolibarr_main_db_host=\'localhost\';
    // $dolibarr_main_db_port=\'3306\';
    // $dolibarr_main_db_name=\'erp_'.$enseigne.'\';
    // $dolibarr_main_db_prefix=\'llx_\';
    // $dolibarr_main_db_user=\''.$username.'\';
    // $dolibarr_main_db_pass=\''.$password.'\';
    // $dolibarr_main_db_type=\'mysqli\';
    // $dolibarr_main_db_character_set=\'utf8\';
    // $dolibarr_main_db_collation=\'utf8_general_ci\';
    // // Authentication settings
    // $dolibarr_main_authentication=\'dolibarr\';

    // //$dolibarr_main_demo=\'autologin,autopass\';
    // // Security settings
    // $dolibarr_main_prod=\'0\';
    // $dolibarr_main_force_https=\'0\';
    // $dolibarr_main_restrict_os_commands=\'mysqldump, mysql, pg_dump, pgrestore\';
    // $dolibarr_nocsrfcheck=\'0\';
    // $dolibarr_main_instance_unique_id=\''.$uniqid.'\';
    // $dolibarr_mailing_limit_sendbyweb=\'0\';

    // //$dolibarr_lib_FPDF_PATH=\'\';
    // //$dolibarr_lib_TCPDF_PATH=\'\';
    // //$dolibarr_lib_FPDI_PATH=\'\';
    // //$dolibarr_lib_TCPDI_PATH=\'\';
    // //$dolibarr_lib_ADODB_PATH=\'\';
    // //$dolibarr_lib_GEOIP_PATH=\'\';
    // //$dolibarr_lib_NUSOAP_PATH=\'\';
    // //$dolibarr_lib_ODTPHP_PATH=\'\';
    // //$dolibarr_lib_ODTPHP_PATHTOPCLZIP=\'\';
    // //$dolibarr_js_CKEDITOR=\'\';
    // //$dolibarr_js_JQUERY=\'\';
    // //$dolibarr_js_JQUERY_UI=\'\';

    // //$dolibarr_font_DOL_DEFAULT_TTF=\'\';
    // //$dolibarr_font_DOL_DEFAULT_TTF_BOLD=\'\';
    // $dolibarr_main_distrib=\'standard\';

    // ';


    // $fp = fopen($file, 'a');//opens file in append mode
    // fwrite($fp, '<'); // fwrite($fp, $confdata); // fclose($fp); // try{ // /* // $pdo=new
        // PDO("mysql:host=" . $servername . " ;dbname=" . $dbname, $username, $password);
//     $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
//     $sql = " UPDATE llx_user SET api_key='$magmaapikey' WHERE rowid=1"; // $pdo ->query($sql);
        // */

        // echo json_encode(array("server_responses" => $param), JSON_UNESCAPED_UNICODE);
        // die();

        // }catch(Exception $e) {

        // echo false;
        // }


        // createDb($dbname, $servername, $username, $password);


        // importDb($dbname, $servername, $username, $password);


        // try{

        // $pdo = new PDO("mysql:host=" . $servername . ";dbname=" . $dbname, $username, $password);
        // $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        // $sql = "UPDATE llx_user SET api_key='$magmaapikey' WHERE rowid=1";
        // $pdo ->query($sql);

        // echo json_encode(array("server_responses" => $param), JSON_UNESCAPED_UNICODE);

        // }catch(Exception $e) {

        // echo false;
        // }







        // function createDb($dbname, $servername, $username, $password,)
        // {



        // try {
        // $sql = "CREATE DATABASE $dbname";


        // $dbco = new PDO("mysql:host=$servername", $username, $password);

        // $dbco->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);


        // $dbco->exec($sql);

        // return true;
        // } catch (PDOException $e) {
        // return false;
        // }
        // }



        // function importDb($dbname, $servername, $username, $password)
        // {
        // try {

        // $pdo = new PDO("mysql:host=" . $servername . ";dbname=" . $dbname, $username, $password);
        // $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);


        // $filename = "erp_installnew.sql";



        // // Connect to MySQL server
        // //$conn2=mysqli_connect($servername, $username, $password) or die('Error connecting to MySQL server: ' .
        // mysqli_error($conn2));
        // // $conn2 = mysqli_connect($servername, $username, $password);
        // // Select database
        // //mysqli_select_db($conn2,$dbname) or die('Error selecting MySQL database: ' . mysqli_error($conn2));
        // // mysqli_select_db($conn2, $dbname);

        // // Temporary variable, used to store current query
        // $templine = '';
        // // Read in entire file
        // $lines = file($filename);
        // // Loop through each line
        // foreach ($lines as $line) {
        // // Skip it if it's a comment
        // if (substr($line, 0, 2) == '--' || $line == '')
        // continue;

        // // Add this line to the current segment
        // $templine .= $line;
        // // If it has a semicolon at the end, it's the end of the query
        // if (substr(trim($line), -1, 1) == ';') {
        // // Perform the query
        // // mysqli_query($conn2,$templine) or print('Error performing query \'<strong>' . $templine . '\': ' .
            // mysqli_error($conn2) . //'<br /><br />');
            // $pdo->query($templine);
            // // Reset temp variable to empty
            // $templine = '';
            // }
            // }
            // return $pdo;
            // } catch (PDOException $e) {
            // return false;
            // }
            // }